### ISSUE TITLE
코드 리뷰를 드립니다

### ISSUE THREAD

**Issue by hyokualexkwon** [seopport/MovieFinder#1]
지원님 안녕하세요? 권혁우 튜터에요! 과제하느라 정말 수고 많으셨어요!

작업하신 내용을 제가 슥삭 살펴보면서 어떤 부분이 괜찮은지, 또는 개선하면 좋을 점이 있을지 적어볼게요. 이 리뷰는 절대로 평가가 아니고, 지원님의 강점을 찾아서 더 발전시키고, 어려운 점은 개선해보고자 하려는 것이니까, 한번 읽어보고 참고해보시면 좋을것 같아요 :)

--

친절한 리드미 작성 감사합니다! 저는 코드를 잘 작성하는것도 좋지만 리드미에 동료(또는 내용을 다 까먹은 미래의 나 ㅋㅋ)가 코드를 잘 읽을 수 있도록 안내하는것도 정말 중요하다고 생각해요. 덕분에 지원님이 생각하신 포인트들을 잘 이해할 수 있게 되었어요.

또, 트러블 슈팅일지도 인상 깊었습니다. 아마 정리하신 덕분에 기억이 오래 남으실거라고 생각해요!

리드미에서 한가지 피드백을 드리자면, 실행방법이 조금 더 구체적으로 작성되면 좋겠다는 생각을 했어요.

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/README.md?plain=1#L34-L40

지금은 디렉토리 이동까지만 적혀있는데, vs code에서 라이브 서버를 켜라! 아니면 html 파일을 클릭해라, npx http-server 를 입력해라! 정도의 앱 실행 가이드가 있으면 더 좋겠네요.

앞으로 수행하실 프로젝트에서는 리드미에 설계 아키텍쳐도 설명하는 내용도 포함되면 더 훌륭할것 같아요. 아키텍쳐라는게 말이 참 어려운데, 모듈을 어떻게 나누었는지, UI 렌더링은 어떻게 작동하는지, API 서버와의 관계 정도를 적으면 아키텍쳐를 설명한다고 볼 수 있을것 같아요.

멋진 리드미 잘 읽었습니다! 👏👏👏

--

<img width="1416" alt="image" src="https://github.com/seopport/MovieFinder/assets/17868599/2fbc0e28-d648-4cb8-ab15-4d8723f36f5d">

검색 결과가 없을때, 얼럿이 나타나면서 내용이 사라졌다가 얼럿 확인을 누르고나면 다시 모든 결과가 나타나는 현상이 어색해요. 차라리 검색 결과가 없으면 기존의 내용은 변화시키지 않고 그대로 두면 어떨까요?

--

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/src/script.js#L34

함수의 이름이 파스칼 케이스인데, 자바스크립트에서는 보통 생성자 함수를 선언할 때만 파스칼 케이스를 쓰는게 컨벤션이에요. [참고](https://ko.javascript.info/constructor-new). 물론 동작은 잘 하지만, 컨벤션에 맞춰 작성하면 동료의 코드 읽기 부하를 줄여줄 수 있을꺼에요. 
이 함수는 심플하게 renderCards 라고 이름지어도 좋을것 같습니다.

--

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/src/script.js#L13-L24

API를 호출하고 그 결과값을 반환하는 함수만으로 따로 분리해낸 점이 좋은것 같습니다. 이 함수는 API를 호출해서 그 결과값을 파싱해서 반환하는 아주 작은 역할만을 하고 있네요. 이렇게 함수가 역할이 작고 단순할수록 복잡함이 줄어든다고 생각해요. 

한가지 피드백을 드리자면, `data["results"];` 대신에 `data.results`라고 작성하면 좋을것 같아요. 특별한 경우가 아닌이상은 dot notation은 기본으로 사용해보면 좋겠네용.

--

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/src/script.js#L81-L100

이 함수에서는 중간중간에 불필요한 변수들이 선언되고 있네요. 심플하게 이렇게 작성해도 될것 같아요:

```js
/* API를 활용하여 받아온 데이터로 구성한 카드 생성하기 */
const appendCard = async () => {
  try {
    const movieData = await loadJsonMovieData(URL); //loadJsonMovieData 함수로 데이터받아오기
    RenderCards(movieData); //받아온 데이터로 카드 RenderCard
    numOfCards.style = "display: none;";
  } catch (err) {
    (err) => {
      //통신 실패 시
      if (err instanceof HttpError && err.response.status == 404) {
        alert("통신 실패");
      } else {
        throw err;
      }
    };
  }
};

```

또, appendCard 함수는 여러개의 card를 그려내기도 하잖아요? 그러면 함수 이름은 복수형인 appendCards라고 적어줘야 할것 같아요.

하지만 이 함수의 역할을 자세히 들여다보면, API를 호출해서 그 데이터로 UI를 그려내고 있으니까 loadAndRenderMovieCards 정도의 이름이 더 낫지 않을까 싶어요. appendCards는 왠지 DOM을 조작해서 카드UI를 추가하는 역할만을 할 것 같은 느낌이에요.

--

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/style/style.css#L21

그라데이션 예뻐용 ㅎㅎ

--

https://github.com/seopport/MovieFinder/blob/807a34d4c58813b05ae4090333c738070a7c38af/style/style.css#L26-L35

line-height을 큰 높이로 직접 주기보다는, .title 요소를 감싸고 있는 요소인 header에 높이를 주고, .title 을 중앙 정렬 시키는 방향이 더 나을것 같아요.

<img width="1416" alt="image" src="https://github.com/seopport/MovieFinder/assets/17868599/cfc8f9a6-9938-4c81-90c3-1981790fe1ef">

텍스트 셀렉션할 때 셀렉션 박스가 line-height의 높이만큼 영역을 차지하니까 사용자가 보기에 어색할 수 있겠다는 생각이 듭니다.

--

전반적으로 기능이 잘 동작하게 구현하신 점이 인상깊습니다! 처음 접하는 문제들이 꽤 있어서 어려우셨을텐데 잘 하셨네요 ㅎㅎ 정말 고생하셨습니다!

시간이 된다면, 함수를 조금 더 나눠보거나, 로직의 역할별로 모듈을 구분하는 연습을 한번 해보시면 좋을것 같아요. 함수이름 짓기가 어렵다면 그럴때 ChatGPT와 같은 LLM 툴을 사용해보시면 도움이 될꺼에요. 

정말 고생 많으셨습니다! 🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌

**Comment by seopport** [comment]
코드 리뷰 감사합니다 튜터님!! 피드백 주신 내용 토대로 보완해보겠습니다!! 🙇‍♀️🙇‍♀️
